### ISSUE TITLE
Optimize background image

### ISSUE THREAD

**Issue by dandv** [JakeRuth/Personal-website#1]
At 4.6Mb, it's YUGE.

https://squoosh.app/editor reduces it by a factor of 3 with no discernible loss of quality.

**Comment by JakeRuth** [comment]
Thank you for this suggestion!!
I don't find much time to work on this, but I'll do this! Not sure when, maybe this weekend.
I'll update here when I do :)

**Comment by JakeRuth** [comment]
@dandv thats a nifty tool indeed, ~730kb now!
https://github.com/JakeRuth/Personal-website/commit/683a797f29d863389d1f686ed0776388d7122388
